### ISSUE TITLE
Incomplete location_id.schema.json

### ISSUE THREAD

**Issue by Rob89** [openans/cqc-syndication-api#1]
I have just started using the new cqc syndication api and have run into a small problem. The schema for location_id is incomplete. For example, using the example from [the docs](https://anypoint.mulesoft.com/apiplatform/openanswers-co-uk/#/portals/organizations/262a9203-e08f-4d1d-809d-2fc07032e8e8/apis/10878/versions/11228/pages/11312): 

> https://api.cqc.org.uk/public/v1/locations/RJL31

This returns JSON with two properties (`lastReport` and `currentRatings`) not listed in the schema and the schema disallows additional properties which makes the returned JSON invalid. Unfortunately, this means I have to disable my schema validation (which nullifies the point in having a schema in the first place) which is a shame. If I validate against the schema, I get errors on nearly 50% of locations. Without validating against the schemas, the api works perfectly :smile: 

Sorry if this isn't the right place to raise this!

**Comment by openans** [comment]
Hi Rob, Thanks for highlighting this issue.  The schema files have now been updated inline with the API. Please let us know how you get on.

**Comment by Rob89** [comment]
Thanks for fixing that so promptly. It appears to be working with the schema validation now.

I've had a few other schema validation errors on other parts of the API. e.g. /changes/{organisation_type}. Can you double check the other schemas or would you like me to raise separate issues for each of the others I've found?

**Comment by Rob89** [comment]
Nevermind - the changes validation error was my mistake. The location_id schema is definitely fixed.

:shipit:

**Comment by openans** [comment]
Brilliant. Thanks for letting us know. We'll close this issue now. Please feel free to raise another issue if you need. Thanks again for the feedback - it's appreciated.
